# Generated by Django 3.0.7 on 2020-06-13 02:11

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        BtreeGinExtension(),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('semester', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=256)),
                ('professors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('absences', models.IntegerField()),
                ('grade', models.FloatField()),
                ('A1', models.FloatField(null=True)),
                ('A2', models.FloatField(null=True)),
                ('D1', models.FloatField(null=True)),
                ('D2', models.FloatField(null=True)),
                ('D3', models.FloatField(null=True)),
                ('history', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None)),
            ],
        ),
        migrations.AddIndex(
            model_name='class',
            index=django.contrib.postgres.indexes.GinIndex(fields=['professors'], name='grades_clas_profess_8bd42f_gin'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['name'], name='grades_clas_name_4b809a_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['semester'], name='grades_clas_semeste_e2dda6_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['absences'], name='grades_clas_absence_8a33f4_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['grade'], name='grades_clas_grade_ca8f73_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['updated'], name='grades_clas_updated_8133ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('semester', 'name'), name='course'),
        ),
    ]
